Import Library

In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

Dataset (raining)

In [3]:
data = {
    "Temperatur": [10, 25, 15, 20, 18, 20, 22, 24],
    "Angin": [0, 0, 5, 3, 7, 10, 5, 6],
    "Persepsi": ["Dingin", "Panas", "Dingin", "Panas", "Dingin", "Dingin", "Panas", "Panas"]
}

df = pd.DataFrame(data)
df

   Temperatur  Angin Persepsi
0          10      0   Dingin
1          25      0    Panas
2          15      5   Dingin
3          20      3    Panas
4          18      7   Dingin
5          20     10   Dingin
6          22      5    Panas
7          24      6    Panas

Encode Label (Dingin → 0, Panas → 1)

In [4]:
le = LabelEncoder()
df["Persepsi_encode"] = le.fit_transform(df["Persepsi"])
df

   Temperatur  Angin Persepsi  Persepsi_encode
0          10      0   Dingin                0
1          25      0    Panas                1
2          15      5   Dingin                0
3          20      3    Panas                1
4          18      7   Dingin                0
5          20     10   Dingin                0
6          22      5    Panas                1
7          24      6    Panas                1

Pisahkan Fitur dan Label

In [5]:
X = df[["Temperatur", "Angin"]]
y = df["Persepsi_encode"]

Gunakan KNN (K=3 dulu)

In [6]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

Prediksi Persepsi Marry saat suhu 16°C dan angin 3 km/jam

In [7]:
data_test = [[16, 3]]
pred = knn.predict(data_test)
hasil = le.inverse_transform(pred)
hasil

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['Dingin'], dtype=object)

Cari nilai K terbaik (1–7) berdasarkan akurasi

In [8]:
scores = {}

for k in range(1, 8):  # Coba K = 1 sampai 7
    knn = KNeighborsClassifier(n_neighbors=k)

    akurasi = []
    for i in range(len(df)):
        # Leave-one-out
        X_train = X.drop(index=i)
        y_train = y.drop(index=i)
        X_test = X.iloc[[i]]
        y_test = y.iloc[[i]]

        knn.fit(X_train, y_train)
        y_pred = knn.predict(X_test)
        akurasi.append(y_pred[0] == y_test.values[0])

    scores[k] = sum(akurasi) / len(akurasi)

scores

{1: np.float64(1.0),
 2: np.float64(0.875),
 3: np.float64(0.75),
 4: np.float64(0.625),
 5: np.float64(0.75),
 6: np.float64(0.25),
 7: np.float64(0.0)}

Ambil nilai K terbaik

In [9]:
best_k = max(scores, key=scores.get)
best_k, scores[best_k]

(1, np.float64(1.0))